# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created: Fri Feb 11 19:42:12 2011
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(643, 468)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.stations_tab = QtGui.QWidget()
        self.stations_tab.setObjectName("stations_tab")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.stations_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stationsTableView = ExtTableView(self.stations_tab)
        self.stationsTableView.setObjectName("stationsTableView")
        self.verticalLayout_2.addWidget(self.stationsTableView)
        self.tabWidget.addTab(self.stations_tab, "")
        self.catch_tab = QtGui.QWidget()
        self.catch_tab.setObjectName("catch_tab")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.catch_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.catchTableView = ExtTableView(self.catch_tab)
        self.catchTableView.setObjectName("catchTableView")
        self.verticalLayout_3.addWidget(self.catchTableView)
        self.tabWidget.addTab(self.catch_tab, "")
        self.bio_tab = QtGui.QWidget()
        self.bio_tab.setObjectName("bio_tab")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.bio_tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        #self.comboBox = QtGui.QComboBox(self.bio_tab)
        #self.comboBox.setObjectName("comboBox")
        #self.comboBox.addItem("")
        #self.comboBox.addItem("")
        #self.comboBox.addItem("")
        #self.comboBox.addItem("")
        #self.verticalLayout_4.addWidget(self.comboBox)
        self.bioTableView = ExtTableView(self.bio_tab)
        self.bioTableView.setObjectName("bioTableView")
        self.bioTableView.setSortingEnabled(True)
        self.verticalLayout_4.addWidget(self.bioTableView)
        self.tabWidget.addTab(self.bio_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 643, 18))
        self.menubar.setObjectName("menubar")
        self.filemenu = QtGui.QMenu(self.menubar)
        self.filemenu.setObjectName("filemenu")
        self.editmenu = QtGui.QMenu(self.menubar)
        self.editmenu.setObjectName("editmenu")
        self.listmenu = QtGui.QMenu(self.menubar)
        self.listmenu.setObjectName("listmenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.newstation = QtGui.QAction(MainWindow)
        self.newstation.setObjectName("newstation")
        self.newspecies = QtGui.QAction(MainWindow)
        self.newspecies.setObjectName("newspecies")
        self.newbio = QtGui.QAction(MainWindow)
        self.newbio.setObjectName("newbio")
        self.action_5 = QtGui.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.importdata = QtGui.QAction(MainWindow)
        self.importdata.setObjectName("importdata")
        self.exportdata = QtGui.QAction(MainWindow)
        self.exportdata.setObjectName("exportdata")
        self.commitdata = QtGui.QAction(MainWindow)
        self.commitdata.setObjectName("commitdata")
        self.quitapp = QtGui.QAction(MainWindow)
        self.quitapp.setObjectName("quitapp")
        self.undoaction = QtGui.QAction(MainWindow)
        self.undoaction.setObjectName("undoaction")
        self.redoaction = QtGui.QAction(MainWindow)
        self.redoaction.setObjectName("redoaction")
        self.cropaction = QtGui.QAction(MainWindow)
        self.cropaction.setObjectName("cropaction")
        self.copyaction = QtGui.QAction(MainWindow)
        self.copyaction.setObjectName("copyaction")
        self.insertaction = QtGui.QAction(MainWindow)
        self.insertaction.setObjectName("insertaction")
        self.deleteaction = QtGui.QAction(MainWindow)
        self.deleteaction.setObjectName("deleteaction")
        self.selectallaction = QtGui.QAction(MainWindow)
        self.selectallaction.setObjectName("selectallaction")
        self.setupaction = QtGui.QAction(MainWindow)
        self.setupaction.setObjectName("setupaction")
        self.species = QtGui.QAction(MainWindow)
        self.species.setObjectName("species")
        self.gear = QtGui.QAction(MainWindow)
        self.gear.setObjectName("gear")
        self.ground = QtGui.QAction(MainWindow)
        self.ground.setObjectName("ground")
        self.disease = QtGui.QAction(MainWindow)
        self.disease.setObjectName("disease")
        self.observer = QtGui.QAction(MainWindow)
        self.observer.setObjectName("observer")
        self.ship = QtGui.QAction(MainWindow)
        self.ship.setObjectName("ship")
        self.filemenu.addAction(self.newstation)
        self.filemenu.addAction(self.newspecies)
        self.filemenu.addAction(self.newbio)
        self.filemenu.addSeparator()
        self.filemenu.addAction(self.importdata)
        self.filemenu.addAction(self.exportdata)
        self.filemenu.addAction(self.commitdata)
        self.filemenu.addSeparator()
        self.filemenu.addAction(self.quitapp)
        self.editmenu.addAction(self.undoaction)
        self.editmenu.addAction(self.redoaction)
        self.editmenu.addSeparator()
        self.editmenu.addAction(self.cropaction)
        self.editmenu.addAction(self.copyaction)
        self.editmenu.addAction(self.insertaction)
        self.editmenu.addAction(self.deleteaction)
        self.editmenu.addAction(self.selectallaction)
        self.editmenu.addSeparator()
        self.editmenu.addAction(self.setupaction)
        self.listmenu.addAction(self.species)
        self.listmenu.addAction(self.gear)
        self.listmenu.addAction(self.ground)
        self.listmenu.addAction(self.disease)
        self.listmenu.addAction(self.observer)
        self.listmenu.addAction(self.ship)
        self.menubar.addAction(self.filemenu.menuAction())
        self.menubar.addAction(self.editmenu.menuAction())
        self.menubar.addAction(self.listmenu.menuAction())

        #переключение между табами
        self.prev_tab = QtGui.QAction(MainWindow)
        self.next_tab = QtGui.QAction(MainWindow)
        self.prev_tab.setObjectName('prev_tab')
        self.next_tab.setObjectName('next_tab')
        self.prev_tab.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Left", None, QtGui.QApplication.UnicodeUTF8))
        MainWindow.addAction(self.prev_tab)
        self.next_tab.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Right", None, QtGui.QApplication.UnicodeUTF8))
        MainWindow.addAction(self.next_tab)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.stations_tab), QtGui.QApplication.translate("MainWindow", "Станции", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.catch_tab), QtGui.QApplication.translate("MainWindow", "Уловы", None, QtGui.QApplication.UnicodeUTF8))
        #self.comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "crab", None, QtGui.QApplication.UnicodeUTF8))
        #self.comboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "krill", None, QtGui.QApplication.UnicodeUTF8))
        #self.comboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "krevet", None, QtGui.QApplication.UnicodeUTF8))
        #self.comboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "craboid", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.bio_tab), QtGui.QApplication.translate("MainWindow", "Биоанализы", None, QtGui.QApplication.UnicodeUTF8))
        self.filemenu.setTitle(QtGui.QApplication.translate("MainWindow", "Файл", None, QtGui.QApplication.UnicodeUTF8))
        self.editmenu.setTitle(QtGui.QApplication.translate("MainWindow", "Правка", None, QtGui.QApplication.UnicodeUTF8))
        self.listmenu.setTitle(QtGui.QApplication.translate("MainWindow", "Списки", None, QtGui.QApplication.UnicodeUTF8))
        self.newstation.setText(QtGui.QApplication.translate("MainWindow", "Новая станция", None, QtGui.QApplication.UnicodeUTF8))
        self.newspecies.setText(QtGui.QApplication.translate("MainWindow", "Новый вид на станции", None, QtGui.QApplication.UnicodeUTF8))
        self.newbio.setText(QtGui.QApplication.translate("MainWindow", "Новый биоанализ", None, QtGui.QApplication.UnicodeUTF8))
        self.action_5.setText(QtGui.QApplication.translate("MainWindow", "Настройки", None, QtGui.QApplication.UnicodeUTF8))
        self.importdata.setText(QtGui.QApplication.translate("MainWindow", "Импорт", None, QtGui.QApplication.UnicodeUTF8))
        self.exportdata.setText(QtGui.QApplication.translate("MainWindow", "Экспорт", None, QtGui.QApplication.UnicodeUTF8))
        self.commitdata.setText(QtGui.QApplication.translate("MainWindow", "Сохранить", None, QtGui.QApplication.UnicodeUTF8))
        self.quitapp.setText(QtGui.QApplication.translate("MainWindow", "Выйти", None, QtGui.QApplication.UnicodeUTF8))
        self.undoaction.setText(QtGui.QApplication.translate("MainWindow", "Отменить", None, QtGui.QApplication.UnicodeUTF8))
        self.undoaction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Z", None, QtGui.QApplication.UnicodeUTF8))
        self.redoaction.setText(QtGui.QApplication.translate("MainWindow", "Повторить", None, QtGui.QApplication.UnicodeUTF8))
        self.redoaction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Y", None, QtGui.QApplication.UnicodeUTF8))
        self.cropaction.setText(QtGui.QApplication.translate("MainWindow", "Вырезать", None, QtGui.QApplication.UnicodeUTF8))
        self.copyaction.setText(QtGui.QApplication.translate("MainWindow", "Копировать", None, QtGui.QApplication.UnicodeUTF8))
        self.insertaction.setText(QtGui.QApplication.translate("MainWindow", "Вставить", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteaction.setText(QtGui.QApplication.translate("MainWindow", "Удалить", None, QtGui.QApplication.UnicodeUTF8))
        self.selectallaction.setText(QtGui.QApplication.translate("MainWindow", "Выделить все", None, QtGui.QApplication.UnicodeUTF8))
        self.setupaction.setText(QtGui.QApplication.translate("MainWindow", "Параметры", None, QtGui.QApplication.UnicodeUTF8))
        self.species.setText(QtGui.QApplication.translate("MainWindow", "Виды", None, QtGui.QApplication.UnicodeUTF8))
        self.gear.setText(QtGui.QApplication.translate("MainWindow", "Орудия лова", None, QtGui.QApplication.UnicodeUTF8))
        self.ground.setText(QtGui.QApplication.translate("MainWindow", "Грунты", None, QtGui.QApplication.UnicodeUTF8))
        self.disease.setText(QtGui.QApplication.translate("MainWindow", "Заболевания", None, QtGui.QApplication.UnicodeUTF8))
        self.observer.setText(QtGui.QApplication.translate("MainWindow", "Наблюдатели", None, QtGui.QApplication.UnicodeUTF8))
        self.ship.setText(QtGui.QApplication.translate("MainWindow", "Суда", None, QtGui.QApplication.UnicodeUTF8))

class ExtTableView(QtGui.QTableView):
    def __init__(self, parent=None, *args):
        QtGui.QTableView.__init__(self, parent, *args)


    
