# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trip_setup.ui'
#
# Created: Thu Feb 24 14:17:24 2011
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(465, 320)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtGui.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.vesselComboBox = QtGui.QComboBox(self.groupBox)
        self.vesselComboBox.setObjectName("vesselComboBox")
        self.vesselComboBox.addItem("")
        self.vesselComboBox.addItem("")
        self.vesselComboBox.addItem("")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.vesselComboBox)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_3)
        self.tripSpinBox = QtGui.QSpinBox(self.groupBox)
        self.tripSpinBox.setMinimum(1)
        self.tripSpinBox.setMaximum(10000)
        self.tripSpinBox.setObjectName("tripSpinBox")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.tripSpinBox)
        self.yearDateEdit = QtGui.QDateEdit(self.groupBox)
        self.yearDateEdit.setObjectName("yearDateEdit")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.yearDateEdit)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_2)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_4)
        self.surveycomboBox = QtGui.QComboBox(self.groupBox)
        self.surveycomboBox.setObjectName("surveycomboBox")
        self.surveycomboBox.addItem("")
        self.surveycomboBox.addItem("")
        self.surveycomboBox.addItem("")
        self.surveycomboBox.addItem("")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.surveycomboBox)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_5)
        self.objectComboBox = QtGui.QComboBox(self.groupBox)
        self.objectComboBox.setObjectName("objectComboBox")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.objectComboBox)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Настройки рейса", None, QtGui.QApplication.UnicodeUTF8))
        self.vesselComboBox.setItemText(0, QtGui.QApplication.translate("Dialog", "Титаник", None, QtGui.QApplication.UnicodeUTF8))
        self.vesselComboBox.setItemText(1, QtGui.QApplication.translate("Dialog", "Аврора", None, QtGui.QApplication.UnicodeUTF8))
        self.vesselComboBox.setItemText(2, QtGui.QApplication.translate("Dialog", "Летучий Голландец", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "судно", None, QtGui.QApplication.UnicodeUTF8))
        self.yearDateEdit.setDisplayFormat(QtGui.QApplication.translate("Dialog", "yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "номер рейса", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "год", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "тип съемки", None, QtGui.QApplication.UnicodeUTF8))
        self.surveycomboBox.setItemText(0, QtGui.QApplication.translate("Dialog", "ловушечная", None, QtGui.QApplication.UnicodeUTF8))
        self.surveycomboBox.setItemText(1, QtGui.QApplication.translate("Dialog", "траловая", None, QtGui.QApplication.UnicodeUTF8))
        self.surveycomboBox.setItemText(2, QtGui.QApplication.translate("Dialog", "водолазная", None, QtGui.QApplication.UnicodeUTF8))
        self.surveycomboBox.setItemText(3, QtGui.QApplication.translate("Dialog", "комбинированная", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "объект", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Dialog", "Tab 1", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Dialog", "Tab 2", None, QtGui.QApplication.UnicodeUTF8))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Dialog", "Настройки рейса", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Dialog", "Другие настройки", None, QtGui.QApplication.UnicodeUTF8))
